# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c90b41e0dce487b37abf728cf62c4c3365dbd67ecdfb8fe555ffc2b0060f3cd82a11485c1e1e35fa4f6016e80988a3f8c9d7043755872fdba82e2b945b05dc4

test:
  secret_key_base: a6bf1f1dc5bf93f635ee8375d25b457518a1282b55a0b2b43a5a54ed1749851b13734c7a601a2c1953d3c6aa6bc76dbae8e7e37f1958f6ff463257291cce8590

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
